BowlingLeague/Models/Bowler.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace BowlingLeague.Models
{
    public class Bowler
    {
        [Key]
        [Required]
        public int BowlerID { get; set; }
        public string BowlerFirstName { get; set; }
        public string BowlerLastName { get; set; }
        public string BowlerMiddleInit { get; set; }
        public string BowlerAddress { get; set; }
        public string BowlerCity { get; set; }
        public string BowlerState { get; set; }
        public string BowlerZip { get; set; }
        public string BowlerPhoneNumber { get; set; }

        public int TeamID { get; set; }
        public Team Team { get; set; }


    }
}

BowlingLeague/Models/BowlingLeagueDbContext.cs
using System;
using Microsoft.EntityFrameworkCore;

namespace BowlingLeague.Models
{
    public class BowlingLeagueDbContext : DbContext
    {
        public BowlingLeagueDbContext(DbContextOptions<BowlingLeagueDbContext> options) : base(options)
        {
        }

        public DbSet<Bowler> Bowlers { get; set; }
        public DbSet<Team> Teams { get; set; }
    }

}

BowlingLeague/Models/EFBowlersRepository.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BowlingLeague.Models
{
    public class EFBowlersRepository : IBowlersRepository
    {
        private BowlingLeagueDbContext _context { get; set; }

        public EFBowlersRepository (BowlingLeagueDbContext temp)
        {
            _context = temp;
        }

        public IQueryable<Bowler> Bowlers => _context.Bowlers;

        public void SaveBowler(Bowler b)
        {
            _context.SaveChanges();
        }

        public void CreateBowler(Bowler b)
        {
            _context.Add(b);
            _context.SaveChanges();
        }

        public void DeleteBowler(Bowler b)
        {
            _context.Remove(b);
            _context.SaveChanges();
        }
    }
}

BowlingLeague/Models/EFBowlingRepository.cs
using System;
using System.Linq;
using Microsoft.EntityFrameworkCore;

namespace BowlingLeague.Models
{
    public class EFBowlingRepository : IBowlingRepository

    {
        private BowlingLeagueDbContext _context { get; set; }
        public EFBowlingRepository(BowlingLeagueDbContext temp)
        {
            _context = temp;
        }

        public IQueryable<Bowler> Bowlers => _context.Bowlers;
        public IQueryable<Team> Teams => _context.Teams;


        public void SaveBowler(Bowler b)
        {
            _context.Update(b);
            _context.SaveChanges();
        }

        public void DeleteBowler(Bowler b)
        {
            _context.Remove(b);
            _context.SaveChanges();
        }

        public void CreateBowler(Bowler b)
        {
            _context.Add(b);
            _context.SaveChanges();
        }
    }

}

BowlingLeague/Models/IBowlersRepository.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BowlingLeague.Models
{
    public interface IBowlersRepository
    {
        IQueryable<Bowler> Bowlers { get; }

        public void CreateBowler(Bowler b);
        public void SaveBowler(Bowler b);
        public void DeleteBowler(Bowler b);
    }
}

BowlingLeague/Models/IBowlingRepository.cs
using System;
using System.Linq;

namespace BowlingLeague.Models
{
    public interface IBowlingRepository
    {
        IQueryable<Bowler> Bowlers { get; }
        IQueryable<Team> Teams { get; }

        public void SaveBowler(Bowler b);
        public void DeleteBowler(Bowler b);
        public void CreateBowler(Bowler b);
    }
}

BowlingLeague/Models/Team.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace BowlingLeague.Models
{
    public class Team
    {
        [Key]
        [Required]
        public int TeamID { get; set; }
        public string TeamName { get; set; }
        public int CaptainID { get; set; }
    }
}

BowlingLeague/Compontents/LabelViewComponent.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using BowlingLeague.Models;

namespace BowlingLeague.Components
{
    public class LabelViewComponent : ViewComponent
    {
        private IBowlingRepository repo { get; set; }

        public LabelViewComponent(IBowlingRepository temp)
        {
            repo = temp;
        }

        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedTeam = RouteData?.Values["teamName"];
            var label = RouteData?.Values["teamName"];
            return View(label);
        }
    }
}

BowlingLeague/Compontents/TeamsViewComponent.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using BowlingLeague.Models;

namespace BowlingLeague.Components
{
    public class TeamsViewComponent : ViewComponent
    {
        private IBowlingRepository repo { get; set; }

        public TeamsViewComponent(IBowlingRepository temp)
        {
            repo = temp;
        }

        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedTeam = RouteData?.Values["teamName"];
            var teams = repo.Teams
                .Select(x => x.TeamName)
                .Distinct()
                .OrderBy(x => x);
            return View(teams);
        }
    }
}

BowlingLeague/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using BowlingLeague.Models;
using Microsoft.EntityFrameworkCore;


namespace BowlingLeague.Controllers
{
    public class HomeController : Controller
    {
        private IBowlingRepository _repo { get; set; }

        public HomeController(IBowlingRepository temp)
        {
            _repo = temp;
        }

        //public IActionResult Index()
        //{
        //    var bowlers = _repo.Bowlers
        //    .ToList();
        //    return View(bowlers);
        //}

        public IActionResult Index(string teamName)
        {

            //collects list of bowlers, including their teams
            var x = _repo.Bowlers
                .Include(b => b.Team)
                .Where(b => b.Team.TeamName == teamName || teamName == null)
                .OrderBy(b => b.Team.TeamName)
                .ToList();
            


            return View(x);
        }



        [HttpGet]
        public IActionResult CreateBowler()
        {
            //brings in teams list
            ViewBag.Teams = _repo.Teams.ToList();
            return View();
        }

        [HttpPost]
        public IActionResult CreateBowler(Bowler b)
        {

            if (ModelState.IsValid)
            {
                    b.BowlerID = (_repo.Bowlers.Max(b => b.BowlerID)) + 1;
                    _repo.CreateBowler(b);
                    return RedirectToAction("Index");

            }
            else
            {
                ViewBag.Teams = _repo.Teams.ToList();
                return View(b);
            }

        }


        //adds ability to Edit and Delete bowler information

        [HttpGet]
        public IActionResult Edit(int bowlerid)
        {

            ViewBag.Teams = _repo.Teams.ToList();
            var bowler = _repo.Bowlers.Single(x => x.BowlerID == bowlerid);
            return View("CreateBowler", bowler);
        }

        [HttpPost]
        public IActionResult Edit(Bowler update)
        {
            _repo.SaveBowler(update);
            return RedirectToAction("Index");
        }

        public IActionResult Delete(Bowler delete)
        {
            _repo.DeleteBowler(delete);
            
            return RedirectToAction("Index");
        }
    }
}

BowlingLeague/Views/Home/CreateBowler.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Add Bowler";
}
@model BowlingLeague.Models.Bowler

    <!-- this file allows users to add a bowler to the database-->
<div>
    <h1>Please include all neccessary information</h1>
</div>
<div>
    <form method="post">
        @*<input type="hidden" asp-for="BowlerID" value="max + 1" />*@
        <label asp-for="BowlerFirstName">First Name:</label>
        <input asp-for="BowlerFirstName" />
        <br />
        <label asp-for="BowlerMiddleInit">Middle Initial:</label>
        <input asp-for="BowlerMiddleInit" />
        <br />
        <label asp-for="BowlerLastName">Last Name:</label>
        <input asp-for="BowlerLastName" />
        <br />
        <label asp-for="BowlerAddress">Address:</label>
        <input asp-for="BowlerAddress" />
        <br />
        <label asp-for="BowlerCity">City:</label>
        <input asp-for="BowlerCity" />
        <br />
        <label asp-for="BowlerState">State:</label>
        <input asp-for="BowlerState" />
        <br />
        <label asp-for="BowlerZip">Zipcode:</label>
        <input asp-for="BowlerZip" />
        <br />
        <label asp-for="BowlerPhoneNumber">Phone Number:</label>
        <input asp-for="BowlerPhoneNumber" />
        <br />

        <label asp-for="TeamID">Team:</label>
        <select asp-for="TeamID">
            <option value="">Select A Team</option>
            @foreach (Team t in ViewBag.Teams)
            {
                <option value="@t.TeamID">@t.TeamName</option>
            }

        </select>
        <br />

        <button type="submit">Save Bowler Information</button>
    </form>
</div>

BowlingLeague/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
@model List<Bowler>

@*list of bowlers with bowler information*@

<div class="text-center">
    <h1 class="display-4">Bowlers</h1>
</div>

<table class="table table-bordered table-striped">
    <thead class="font-wieght-bold">
        <tr>
            <th>First Name</th>
            <th>Middle Initial</th>
            <th>Last Name</th>
            <th>Address</th>
            <th>City</th>
            <th>State</th>
            <th>Zipcode</th>
            <th>Phone Number</th>
            <th>Team Name</th>
        </tr>
    </thead>


    @foreach (var b in Model)
    {
        <tr>
            <td>@b.BowlerFirstName</td>
            <td>@b.BowlerMiddleInit</td>
            <td>@b.BowlerLastName</td>
            <td>@b.BowlerAddress</td>
            <td>@b.BowlerCity</td>
            <td>@b.BowlerState</td>
            <td>@b.BowlerZip</td>
            <td>@b.BowlerPhoneNumber</td>
            <td>@b.Team.TeamName</td>

            @*each bowler has a button to edit or delete, with an add button at the bottom of the page*@

            <td><a asp-controller="Home" asp-action="Edit" asp-route-bowlerid="@b.BowlerID">Edit</a></td>
            <td><a asp-controller="Home" asp-action="Delete" asp-route-bowlerid="@b.BowlerID">Delete</a></td>
        </tr>
    }
        <tr>
                <td><a asp-controller="Home" asp-action="CreateBowler" class="btn btn-primary">Add New Bowler</a></td>
        </tr>
</table>

BowlingLeague/Views/Shared/Components/Label/Default.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<div class="d-grid gap-2">
    @ViewBag.SelectedTeam
</div>

BowlingLeague/Views/Shared/Components/Teams/Default.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

*@
@{
}
@model IEnumerable<string>

@*buttons and button layout for each team and home*@

<div class="d-grid gap-2">
    <a asp-controller="Home" asp-action="Index" asp-route-teamName=""  class="btn btn-outline-secondary">Home</a>
    <br />
    @foreach (string t in Model)
    {
        <a asp-controller="Home" asp-action="Index" asp-route-teamName="@t" class="btn @(ViewBag.SelectedTeam == t ? "btn-primary" : "btn-outline-secondary")">@t</a>
        <br />
    }
</div>

BowlingLeague/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>

    <head>
        <meta name="viewport" content="width=device-width" />
        <title>
            @ViewBag.Title
        </title>


        <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    </head>

<body>
    <div class="bg-dark text-white p-2">
        <h1><span class="navbar-brand ml-2">Bowling League</span></h1>
    </div>
    <div class="row m-1 p-1">
        @*vc allows app to access vie component to bring in team names and selected team*@
        <div id="teams" class="col-3">
            <h1><vc:teams></vc:teams></h1>
        </div>
        <div class="col-9">
            <div id="label" class="text-lg-left font-weight-bold">
                <h1><vc:label></vc:label></h1>
                </div>
            @RenderBody()
        </div>
    </div>
</body>

</html>